// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRuleSet(arg1) {
  return window['go']['main']['App']['DeleteRuleSet'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function GetBootstrap() {
  return window['go']['main']['App']['GetBootstrap']();
}

export function GetDNSCaptureState() {
  return window['go']['main']['App']['GetDNSCaptureState']();
}

export function ImportLegacyData() {
  return window['go']['main']['App']['ImportLegacyData']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenRuntimeDir() {
  return window['go']['main']['App']['OpenRuntimeDir']();
}

export function PrepareRuntimeAssets() {
  return window['go']['main']['App']['PrepareRuntimeAssets']();
}

export function SaveCloseAction(arg1) {
  return window['go']['main']['App']['SaveCloseAction'](arg1);
}

export function SaveDNSSettings(arg1) {
  return window['go']['main']['App']['SaveDNSSettings'](arg1);
}

export function SaveProxyOptions(arg1) {
  return window['go']['main']['App']['SaveProxyOptions'](arg1);
}

export function SaveSelection(arg1) {
  return window['go']['main']['App']['SaveSelection'](arg1);
}

export function ScanRuleIncludeExecutables() {
  return window['go']['main']['App']['ScanRuleIncludeExecutables']();
}

export function SetDNSCaptureEnabled(arg1) {
  return window['go']['main']['App']['SetDNSCaptureEnabled'](arg1);
}

export function StartSession() {
  return window['go']['main']['App']['StartSession']();
}

export function StopSession() {
  return window['go']['main']['App']['StopSession']();
}

export function UpsertRuleSet(arg1) {
  return window['go']['main']['App']['UpsertRuleSet'](arg1);
}

export function UpsertServer(arg1) {
  return window['go']['main']['App']['UpsertServer'](arg1);
}
