// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteRuleSet(arg1:string):Promise<model.BootstrapState>;

export function DeleteServer(arg1:string):Promise<model.BootstrapState>;

export function GetBootstrap():Promise<model.BootstrapState>;

export function GetDNSCaptureState():Promise<model.DNSCaptureState>;

export function ImportLegacyData():Promise<model.BootstrapState>;

export function OpenDataDir():Promise<void>;

export function OpenRuntimeDir():Promise<void>;

export function PrepareRuntimeAssets():Promise<model.BootstrapState>;

export function SaveCloseAction(arg1:string):Promise<model.BootstrapState>;

export function SaveDNSSettings(arg1:model.DNSSettings):Promise<model.BootstrapState>;

export function SaveProxyOptions(arg1:model.ProxyOptions):Promise<model.BootstrapState>;

export function SaveSelection(arg1:model.SelectionState):Promise<model.BootstrapState>;

export function ScanRuleIncludeExecutables():Promise<Array<string>>;

export function SetDNSCaptureEnabled(arg1:boolean):Promise<model.DNSCaptureState>;

export function StartSession():Promise<model.BootstrapState>;

export function StopSession():Promise<model.BootstrapState>;

export function UpsertRuleSet(arg1:model.RuleSet):Promise<model.BootstrapState>;

export function UpsertServer(arg1:model.SocksServer):Promise<model.BootstrapState>;
